### ISSUE TITLE
Cannot start ROOT 6.26.0 (Linux)

### ISSUE THREAD

**Issue by swertz** [conda-forge/root-feedstock#163] opened 2022-03-07 10:46 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have successfully installed ROOT 6.26 in a miniconda environment using:
```
conda create --name root626
conda activate root626
conda install -c conda-forge root
```

However, it is not possible to launch `root` or any root-based command (`rootbrowse` etc.); it crashes with:
```
Failure value returned from cantFail wrapped call
UNREACHABLE executed at /home/swertz/.miniconda3/envs/root626/include/llvm/Support/Error.h:731!
```

I should note that there is no such folder as `/home/swertz/.miniconda3/envs/root626/include/llvm` !

### Installed packages

```shell
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   h5bd9786_13    conda-forge
afterimage                1.21              ha9998ff_1003    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39h3811e60_1    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
binutils                  2.36.1               hdd6e379_2    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                 hf3e587d_6    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-compiler                1.4.1                h166bdaf_0    conda-forge
ca-certificates           2022.2.1             h06a4308_0  
cairo                     1.16.0            ha00ac49_1009    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
compilers                 1.4.1                ha770c72_0    conda-forge
cxx-compiler              1.4.1                h924138e_0    conda-forge
davix                     0.8.0                h40e8b40_3    conda-forge
debugpy                   1.5.1            py39he80948d_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.4.6                h27087fc_0    conda-forge
fftw                      3.3.10          nompi_h77c792f_102    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.96              ha180cfb_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fortran-compiler          1.4.1                h2a4ca65_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
ftgl                      2.4.0                hbcb1f35_0    conda-forge
gcc                       10.3.0               he2824d0_6    conda-forge
gcc_impl_linux-64         10.3.0              hf2f2afa_13    conda-forge
gcc_linux-64              10.3.0               hc39de41_6    conda-forge
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gfortran                  10.3.0               h18518b4_6    conda-forge
gfortran_impl_linux-64    10.3.0              h73f4979_13    conda-forge
gfortran_linux-64         10.3.0               hb09a455_6    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gl2ps                     1.4.2                h0708190_0    conda-forge
glew                      2.1.0                h9c3ff4c_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.50.0               h8e749b2_2    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gsoap                     2.8.119              h90a1d37_0    conda-forge
gtk2                      2.24.33              h90689f9_2    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
gxx                       10.3.0               he2824d0_6    conda-forge
gxx_impl_linux-64         10.3.0              hf2f2afa_13    conda-forge
gxx_linux-64              10.3.0               h2593f52_6    conda-forge
harfbuzz                  3.4.0                hb4a5f5f_0    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
importlib-metadata        4.11.2           py39hf3d152e_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.9.1            py39hef51801_0    conda-forge
ipyparallel               8.2.0              pyhd8ed1ab_0    conda-forge
ipython                   8.1.1            py39hf3d152e_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1           py39hf3d152e_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py39hf3d152e_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kernel-headers_linux-64   3.10.0              h4a8ded7_13    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.2               h3790be6_4    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.81.0               h2574ce0_0    conda-forge
libcxx                    12.0.1               h4bd325d_1    conda-forge
libcxxabi                 12.0.1               ha770c72_1    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     10.3.0              he6cfe16_13    conda-forge
libgcc-ng                 11.2.0              h1d223b6_13    conda-forge
libgd                     2.3.3                h3cfcdeb_1    conda-forge
libgfortran-ng            11.2.0              h69a702a_13    conda-forge
libgfortran5              11.2.0              h5c6108e_13    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   11.2.0              h1d223b6_13    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libllvm11                 11.1.0               h3826bc1_0  
libllvm9                  9.0.1           default_hc23dcda_7    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
librsvg                   2.52.5               h0a9e6e8_2    conda-forge
libsanitizer              10.3.0              h26c7422_13    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-devel_linux-64  10.3.0              he6cfe16_13    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_13    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvm                      11.1.0               h06a4308_0  
llvmlite                  0.38.0           py39h1bbdace_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.1.0            py39hb9d737c_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
metakernel                0.28.2             pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h3811e60_1005    conda-forge
nbclient                  0.5.12             pyhd8ed1ab_0    conda-forge
nbconvert                 6.4.2            py39hf3d152e_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
nlohmann_json             3.10.5               h9c3ff4c_0    conda-forge
notebook                  6.4.8              pyha770c72_0    conda-forge
numba                     0.55.1           py39h56b8d98_0    conda-forge
numpy                     1.21.5           py39haac66dc_0    conda-forge
openssl                   1.1.1m               h7f8727e_0  
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandoc                    2.17.1.1             ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.50.4               h4dcc4a0_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
portalocker               2.4.0            py39hf3d152e_0    conda-forge
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
psutil                    5.9.0            py39h3811e60_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py39h3811e60_0    conda-forge
pythia8                   8.305            py39he80948d_0    conda-forge
python                    3.9.10          h85951f9_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pyzmq                     22.3.0           py39h37b5a0c_1    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
root                      6.26.0           py39h1832856_0    conda-forge
root_base                 6.26.0           py39hd053ead_0    conda-forge
scitokens-cpp             0.6.3                h00015f2_2    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                60.9.3           py39hf3d152e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
sysroot_linux-64          2.17                h4a8ded7_13    conda-forge
tbb                       2021.5.0             h4bd325d_0    conda-forge
terminado                 0.13.2           py39hf3d152e_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.1              py39h3811e60_2    conda-forge
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
vdt                       0.4.3                h9c3ff4c_0    conda-forge
vector-classes            1.4.2                h4bd325d_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.6.12               h36c2ea0_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxcursor           1.2.0                h516909a_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxft               2.3.4                h8aea5ac_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xrootd                    5.4.1            py39hbfe9b54_0    conda-forge
xxhash                    0.8.0                h7f98852_3    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

### Environment info

```shell
active environment : root626
    active env location : /home/swertz/.miniconda3/envs/root626
            shell level : 1
       user config file : /home/swertz/.condarc
 populated config files : /home/swertz/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.34=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/swertz/.miniconda3  (writable)
      conda av data dir : /home/swertz/.miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/swertz/.miniconda3/pkgs
                          /home/swertz/.conda/pkgs
       envs directories : /home/swertz/.miniconda3/envs
                          /home/swertz/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.7 Linux/5.13.0-30-generic ubuntu/21.10 glibc/2.34
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by swertz** [comment] 2022-03-07 11:46
I've tried with `root=6.24.6` in a new environment and that works fine!
```
(root624)  swertz@swertz-thinkpad  ~  root
root [0] gROOT->GetVersion()
(const char *) "6.24/06"
```

Here is a dump of my environment (after activating the conda env): [env.txt](https://github.com/conda-forge/root-feedstock/files/8197381/env.txt)
I don't see anything obviously problematic, apart from `/home/swertz/.local/bin` appearing in the `PATH`: there is some python stuff in there that could create conflicts - not sure how it got there - but it's located after the conda paths in `PATH` anyway.

> (FYI: Using [mamba install](https://github.com/mamba-org/mamba/#mamba) instead of conda install is considerably faster, see the link for details?)

Thanks, forgot about that!

**Comment by chrisburr** [comment] 2022-03-08 12:42
Thanks @swertz for the help debugging. It turns out it's caused by the leading `.` in the miniconda directory which cause's ROOT's path resolution to fail.

The fix is in: https://github.com/root-project/root/pull/10073

**Closed** 2022-05-10 10:17 UTC
Labels: bug
