### ISSUE TITLE
Error while compiling software that uses ROOT libraries

### ISSUE THREAD

**Issue by surrutiaquir** [conda-forge/root-feedstock#103] opened 2020-07-19 02:44 UTC
Issue:

I tried to install a software (Delphes) that uses ROOT libraries but it crashes. If I use a non-conda version of ROOT (i.e., building using make) then there is no issue. One of the error messages I get is the following: 

```
>> Generating tmp/classes/ClassesDict.cc
In file included from input_line_14:1:
In file included from /Users/surrutiaquir/miniconda3/include/TStreamerInfo.h:21:
In file included from /Users/surrutiaquir/miniconda3/include/TVirtualCollectionProxy.h:26:
In file included from /Users/surrutiaquir/miniconda3/include/TClassRef.h:24:
In file included from /Users/surrutiaquir/miniconda3/include/TClass.h:31:
In file included from /Users/surrutiaquir/miniconda3/bin/../include/c++/v1/unordered_set:367:
/Users/surrutiaquir/Documents/Programs/MG5_aMC_v2_7_3_py3/Delphes/version:1:1: error: expected unqualified-id
3.4.2
^
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/surrutiaquir/miniconda3:
#
# Name                    Version                   Build  Channel
afterimage                1.21              hf755657_1003    conda-forge
appnope                   0.1.0                    py37_0  
attrs                     19.3.0                     py_0  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
bleach                    3.1.5                      py_0  
brotlipy                  0.7.0           py37haf1e3a3_1000  
bzip2                     1.0.8                h1de35cc_0  
c-compiler                1.1.0                h1239861_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
cctools                   949.0.1              h22b1bf0_0    conda-forge
cctools_osx-64            949.0.1              h5ba7a2e_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hb5b8e2f_0  
cfitsio                   3.470                h84d2f63_2    conda-forge
chardet                   3.0.4                 py37_1003  
clang                     9.0.1           default_hf57f61e_0    conda-forge
clang-tools               9.0.1           default_hf57f61e_0    conda-forge
clang_osx-64              9.0.1                h05bbb7f_0    conda-forge
clangxx                   9.0.1           default_hf57f61e_0    conda-forge
clangxx_osx-64            9.0.1                h05bbb7f_2    conda-forge
compiler-rt               9.0.1                h6a512c6_3    conda-forge
compiler-rt_osx-64        9.0.1                h99342c6_3    conda-forge
compilers                 1.1.0                         0    conda-forge
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-package-handling    1.6.1            py37h1de35cc_0  
cryptography              2.9.2            py37ha12b0ac_0  
cxx-compiler              1.1.0                h707564b_0    conda-forge
cycler                    0.10.0                   py37_0  
davix                     0.7.6                h61356a0_0    conda-forge
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py37_0  
fastcache                 1.1.0            py37h1de35cc_0  
fftw                      3.3.8           nompi_h44ae4c8_1111    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
fortran-compiler          1.1.0                he991be0_0    conda-forge
freetype                  2.10.2               ha233b18_0  
fribidi                   1.0.9                haf1e3a3_0  
gdk-pixbuf                2.38.2               h306395f_4    conda-forge
gettext                   0.19.8.1             h15daf44_3  
gfortran_impl_osx-64      7.3.0                hf4212f2_2    conda-forge
gfortran_osx-64           7.3.0               h22b1bf0_11    conda-forge
giflib                    5.2.1                h0b31af3_2    conda-forge
glew                      2.1.0                h4a8c4bd_0    conda-forge
glib                      2.63.1               hd977a24_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py37h6ef4df4_2  
gobject-introspection     1.56.1           py37hfc82f85_2  
graphite2                 1.3.13               h2098e52_0  
graphviz                  2.42.3               h98dfb87_0    conda-forge
gsl                       2.6                  ha2d443c_0    conda-forge
harfbuzz                  2.4.0                hd8d2a14_3    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.10                       py_0  
importlib-metadata        1.7.0                    py37_0  
importlib_metadata        1.7.0                         0  
intel-openmp              2019.4                      233  
ipykernel                 5.3.2            py37h5ca1d4c_0  
ipyparallel               6.3.0            py37hc8dfbb8_0    conda-forge
ipython                   7.16.1           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
isl                       0.19                          0    conda-forge
jedi                      0.17.1                   py37_0  
jinja2                    2.11.2                     py_0  
joblib                    0.16.0                     py_0  
jpeg                      9d                   h0b31af3_0    conda-forge
json5                     0.9.5                      py_0  
jsonschema                3.2.0                    py37_0  
jupyter_client            6.1.6                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                2.1.4                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0  
kiwisolver                1.2.0            py37h04f5b5a_0  
krb5                      1.16.4               hddcf347_0  
ld64                      530                           0    conda-forge
ld64_osx-64               530                  h3c32e8a_0    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf57f61e_0    conda-forge
libcroco                  0.6.13               h9035b8d_1    conda-forge
libcurl                   7.67.0               h051b688_0  
libcxx                    9.0.1                         1    conda-forge
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h0a44026_6  
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15                 hdd342a3_7  
liblapack                 3.8.0                    14_mkl    conda-forge
libllvm9                  9.0.1                h7475705_1    conda-forge
libpng                    1.6.37               ha441bb4_0  
libpq                     12.2                 h554dc5a_0    conda-forge
librsvg                   2.49.2               h1ccd86b_0    conda-forge
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.1.0                hcb84e12_0  
libxml2                   2.9.10               h53d96d6_0    conda-forge
llvm-openmp               10.0.0               h28b9765_0  
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.1.3                    py37_0  
matplotlib-base           3.1.3            py37h9aa3819_0  
metakernel                0.24.4             pyh9f0ad1d_0    conda-forge
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.2                h9066e36_1  
mpmath                    1.1.0                    py37_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.7                      py_0  
ncurses                   6.1                  h0a44026_1  
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numpy                     1.18.5           py37h7687784_0    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
packaging                 20.4                       py_0  
pandas                    1.0.3            py37h6c726b0_0  
pandoc                    2.10                          0  
pandocfilters             1.4.2                    py37_1  
pango                     1.42.4               hc249df1_1  
parso                     0.7.0                      py_0  
pcre                      8.43                 h0a44026_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pip                       20.1.1                   py37_1  
pixman                    0.38.0               h1de35cc_0  
portalocker               1.7.0            py37hc8dfbb8_0    conda-forge
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.5                      py_0  
ptyprocess                0.6.0                    py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.20                       py_2  
pygments                  2.6.1                      py_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyrsistent                0.16.0           py37h1de35cc_0  
pysocks                   1.7.1                    py37_0  
pythia8                   8.244            py37h570ac47_1    conda-forge
python                    3.7.6           h90870a6_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0  
python.app                2                       py37_10  
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                     py_0  
pyzmq                     18.1.1           py37h0a44026_0  
qt                        5.12.5               h514805e_3    conda-forge
readline                  8.0                  h1de35cc_0  
requests                  2.24.0                     py_0  
root                      6.18.04         py37h95b5a52_22    conda-forge
root-binaries             6.18.04         py37h95b5a52_22    conda-forge
root-dependencies         6.18.04         py37h95b5a52_22    conda-forge
root_base                 6.18.04         py37he966776_22    conda-forge
root_numpy                4.8.0            py37hbf1eeb5_3    conda-forge
ruamel_yaml               0.15.87          py37haf1e3a3_1  
scikit-learn              0.22.1           py37h27c97d8_0  
scipy                     1.4.1            py37hce1b9e5_3    conda-forge
send2trash                1.5.0                    py37_0  
setuptools                49.2.0                   py37_0  
six                       1.15.0                     py_0  
sqlite                    3.31.1               ha441bb4_0  
sympy                     1.5.1                    py37_0  
tapi                      1000.10.8            ha1b3eb9_4    conda-forge
tbb                       2020.0               h04f5b5a_0  
tbb-devel                 2020.0               h04f5b5a_0  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
tk                        8.6.10               hb0a8c7a_0  
tornado                   6.0.4            py37h1de35cc_1  
tqdm                      4.47.0                     py_0  
traitlets                 4.3.3                    py37_0  
urllib3                   1.25.9                     py_0  
vdt                       0.4.3                h6de7cb9_0    conda-forge
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
wheel                     0.34.2                   py37_0  
xrootd                    4.11.3           py37h945a9f6_1    conda-forge
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
zeromq                    4.3.1                h0a44026_3  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
    active env location : /Users/surrutiaquir/miniconda3
            shell level : 1
       user config file : /Users/surrutiaquir/.condarc
 populated config files : /Users/surrutiaquir/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __osx=10.15.6
       base environment : /Users/surrutiaquir/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/surrutiaquir/miniconda3/pkgs
                          /Users/surrutiaquir/.conda/pkgs
       envs directories : /Users/surrutiaquir/miniconda3/envs
                          /Users/surrutiaquir/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.7.6 Darwin/19.6.0 OSX/10.15.6
                UID:GID : 501:20
             netrc file : /Users/surrutiaquir/.netrc
           offline mode : False
```
</details>

**Comment by chrisburr** [comment] 2020-07-20 06:58
I'd suggest using the CMake configuration instead of the Makefile as it's more likely to do things correctly. The steps below work for me:


1. Prepare the conda environment

```bash
conda create --name test-delphes-build root cmake
conda activate test-delphes-build
```

2. Pick where to install and prepare the sources

```bash
MY_DIRECTORY="$HOME/Development"

cd MY_DIRECTORY
git clone git@github.com:delphes/delphes.git
cd delphes/
mkdir build
cd build/
```

3. Build and install:

```bash
cmake -DCMAKE_INSTALL_PREFIX="${MY_DIRECTORY}/delphes-install" ..
make  -j6
make  -j6 install
```

4. Run a quick test

```bash
cd "${MY_DIRECTORY}"

wget http://cp3.irmp.ucl.ac.be/downloads/z_ee.hep.gz
gunzip z_ee.hep.gz

delphes-install/bin/DelphesSTDHEP delphes-install/cards/delphes_card_CMS.tcl delphes_output.root z_ee.hep
```

**Comment by surrutiaquir** [comment] 2020-07-20 15:27
Thank you for your suggestion. I tried it but it crashes again when running
```
make
make install
```

This is the error message:
```
(test-delphes-build) Seba-Macbook:build surrutiaquir$ make
[  0%] Generating Pythia8Dict.cxx, libPythia8Dict_rdict.pcm, libPythia8Dict.rootmap
In file included from input_line_1:1:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/new:90:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/exception:80:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/cstddef:37:
/Users/surrutiaquir/Downloads/delphes/version:1:1: error: expected unqualified-id
3.4.2
^
In file included from input_line_1:1:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/new:90:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/exception:80:
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
      ~~^
In file included from input_line_1:1:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/new:90:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/exception:80:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/cstddef:110:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/type_traits:418:
/Users/surrutiaquir/Downloads/delphes/version:1:1: error: expected unqualified-id
3.4.2
^
In file included from input_line_1:1:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/new:90:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/exception:81:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/cstdlib:85:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/stdlib.h:100:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/math.h:312:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/limits:121:
/Users/surrutiaquir/Downloads/delphes/version:1:1: error: expected unqualified-id
3.4.2
^
In file included from input_line_1:1:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/new:90:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/exception:83:
/Users/surrutiaquir/Downloads/delphes/version:1:1: error: expected unqualified-id
3.4.2
^
In file included from input_line_1:1:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/new:93:
/Users/surrutiaquir/Downloads/delphes/version:1:1: error: expected unqualified-id
3.4.2
^
In file included from input_line_3:1:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/include/RtypesCore.h:27:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/stddef.h:45:
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/etc//cling/lib/clang/5.0.0/include/stddef.h:51:9: error: unknown type name '__PTRDIFF_TYPE__'
typedef __PTRDIFF_TYPE__ ptrdiff_t;
        ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/etc//cling/lib/clang/5.0.0/include/stddef.h:62:9: error: unknown type name '__SIZE_TYPE__'
typedef __SIZE_TYPE__ size_t;
        ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/etc//cling/lib/clang/5.0.0/include/stddef.h:90:9: error: unknown type name '__WCHAR_TYPE__'
typedef __WCHAR_TYPE__ wchar_t;
        ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/etc//cling/lib/clang/5.0.0/include/stddef.h:90:24: error: expected unqualified-id
typedef __WCHAR_TYPE__ wchar_t;
                       ^
In file included from input_line_3:2:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string:504:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string_view:175:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/__string:57:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/algorithm:639:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:46:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/cstddef:37:
/Users/surrutiaquir/Downloads/delphes/version:1:1: error: expected unqualified-id
3.4.2
^
In file included from input_line_3:2:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string:504:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string_view:175:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/__string:57:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/algorithm:639:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:46:
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/cstddef:47:1: error: unknown type name '_LIBCPP_BEGIN_NAMESPACE_STD'
_LIBCPP_BEGIN_NAMESPACE_STD
^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/cstddef:49:1: error: expected unqualified-id
using ::ptrdiff_t;
^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/cstddef:60:1: error: unknown type name '_LIBCPP_END_NAMESPACE_STD'
_LIBCPP_END_NAMESPACE_STD
^
In file included from input_line_3:2:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string:504:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string_view:175:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/__string:57:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/algorithm:639:
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:52:1: error: expected unqualified-id
namespace std  // purposefully not versioned
^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:60:5: error: expected expression
    const _Ep* __begin_;
    ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:58:28: error: variable has incomplete type 'class _LIBCPP_TEMPLATE_VIS'
class _LIBCPP_TEMPLATE_VIS initializer_list
                           ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:58:7: note: forward declaration of 'std::_LIBCPP_TEMPLATE_VIS'
class _LIBCPP_TEMPLATE_VIS initializer_list
      ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:96:8: error: unknown type name '_LIBCPP_INLINE_VISIBILITY'
inline _LIBCPP_INLINE_VISIBILITY
       ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:97:30: error: expected ';' at end of declaration
_LIBCPP_CONSTEXPR_AFTER_CXX11
                             ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:98:7: error: unknown type name '_Ep'
const _Ep*
      ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:99:24: error: use of undeclared identifier '_Ep'
begin(initializer_list<_Ep> __il) _NOEXCEPT
                       ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:99:24: error: use of undeclared identifier '_Ep'
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/initializer_list:99:35: error: expected function body after function declarator
begin(initializer_list<_Ep> __il) _NOEXCEPT
                                  ^
In file included from input_line_3:2:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string:504:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string_view:175:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/__string:57:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/algorithm:640:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/type_traits:418:
/Users/surrutiaquir/Downloads/delphes/version:1:1: error: expected unqualified-id
3.4.2
^
In file included from input_line_3:2:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string:504:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/string_view:175:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/__string:57:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/algorithm:640:
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/type_traits:427:49: error: variable has incomplete type 'class _LIBCPP_TEMPLATE_VIS'
template <class _Tp> class _LIBCPP_TEMPLATE_VIS reference_wrapper;
                                                ^
/Users/surrutiaquir/Software/Python/envs/test-delphes-build/bin/../include/c++/v1/type_traits:427:28: note: forward declaration of '_LIBCPP_TEMPLATE_VIS'
template <class _Tp> class _LIBCPP_TEMPLATE_VIS reference_wrapper;
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
In file included from input_line_5:1:
In file included from /Users/surrutiaquir/Software/Python/envs/test-delphes-build/etc//cling/lib/clang/5.0.0/include/assert.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:42:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:81:2: warning: "Unsupported compiler detected" [-W#warnings]
#warning "Unsupported compiler detected"
 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
#error Unsupported architecture
 ^
Error: Error loading the default header files.
make[2]: *** [modules/Pythia8Dict.cxx] Error 1
make[1]: *** [modules/CMakeFiles/modules.dir/all] Error 2
make: *** [all] Error 2
```

Any suggestion is welcome.

**Comment by chrisburr** [comment] 2020-07-21 11:00
Ah sorry I'd missed that your were running on macOS.

The issue is `VERSION` file in the root directory of the repository. Unlike on Linux, most macOS systems use a case-insenstive  file system is case insensitive meaning `delphes/version` and `delphes/VERSION` are the same file.

One of the C++ standard library headers `c++/v1/cstddef` contains:

```cpp
#include <__config>
#include <version>

#if !defined(_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER)
#pragma GCC system_header
#endif
```

At some point during the build delphes passes `-I$HOME/Development/delphes` to the compiler which causes `#include <version>` to resolve to `delphes/VERSION` instead of `c++/v1/version`.

I'm going to close this as it's a bug in the delphes build system. I encourage you to open an issue there pointing them to this comment.

In the meantime, it seems to work if you just delete the `VERSION` file.

**Closed by chrisburr** 2020-07-21 11:00 UTC
