### ISSUE TITLE
Issues installing root with macOS Monterey

### ISSUE THREAD

**Issue by rgarmatt** [conda-forge/root-feedstock#167] opened 2022-04-05 11:03 UTC
### Issue

Issue with macOS Monterey:
After installing root with conda-forge in an anaconda environment, I had some issues to open root and got the following error message:
 
input_line_1:1:2: error: module 'Darwin' uses additional module map
      '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/net.modulemap' used
      when the module was built
#include <new>
 ^
input_line_1:1:2: note: imported by module 'std' in '/opt/anaconda3/envs/med/lib/std.pcm'
Warning in cling::IncrementalParser::CheckABICompatibility():
  Failed to extract C++ standard library version.
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_ABI_VERSION '1'
  Extraction of runtime standard library version was: ''
input_line_2:1:2: fatal error: module file '/opt/anaconda3/envs/med/lib/std.pcm' is out of date and needs to be rebuilt
#include "cling/Interpreter/RuntimeUniverse.h"
 ^
input_line_2:1:2: note: imported by module 'Cling_Runtime_Extra' in
      '/opt/anaconda3/envs/med/lib/Cling_Runtime_Extra.pcm'
input_line_2:1:2: note: imported by module 'Cling_Runtime' in '/opt/anaconda3/envs/med/lib/Cling_Runtime.pcm'
Replaced symbol atexit cannot be found in JIT!
Replaced symbol at_quick_exit cannot be found in JIT!
<<< cling interactive line includer >>>: fatal error: module file '/opt/anaconda3/envs/med/lib/Darwin.pcm' is out of date and needs to be rebuilt
Failed to load module Darwin
Failed to load module std
Failed to load module _Builtin_intrinsics
Failed to load module ROOT_Foundation_C
Failed to load module ROOT_Config
Failed to load module ROOT_Rtypes
Failed to load module ROOT_Foundation_Stage1_NoRTTI
Failed to load module Core
Failed to load module Rint
Failed to load module RIO
Failed to load module MathCore
Failed to load module Hist
Failed to load module Darwin
Failed to load module Unfold
Failed to load module Imt
Failed to load module HistPainter
Failed to load module PyMVA
Failed to load module RHTTPSniff
Failed to load module RDAVIX
Failed to load module RHTTP
Failed to load module FitPanel
Failed to load module ROOTVecOps
Failed to load module ProofDraw
Failed to load module ROOTBrowsable
Failed to load module Quadp
Failed to load module ROOT_Foundation_Stage1_NoRTTI
Failed to load module GeomPainter
Failed to load module Genetic
Failed to load module Eve
Failed to load module TreeViewer
Failed to load module Physics
Failed to load module ROOTNTuple
Failed to load module EG
Failed to load module Tree
Failed to load module HistFactory
Failed to load module Spectrum
Failed to load module Matrix
Failed to load module Html
Failed to load module Hist
Failed to load module GuiHtml
Failed to load module _Builtin_intrinsics
Failed to load module Gpad
Failed to load module TMVAGui
Failed to load module ROOTEve
Failed to load module Fumili
Failed to load module Net
Failed to load module RGL
Failed to load module Geom
Failed to load module Postscript
Failed to load module GCocoa
Failed to load module ROOTGpadv7
Failed to load module RCsg
Failed to load module Cling_Runtime
Failed to load module SPlot
Failed to load module EGPythia8
Failed to load module GeomBuilder
Failed to load module RooFit
Failed to load module ROOT_Config
Failed to load module RooFitMore
Failed to load module Rint
Failed to load module XMLParser
Failed to load module MultiProc
Failed to load module RooStats
Failed to load module Proof
Failed to load module RooFitRDataFrameHelpers
Failed to load module FITSIO
Failed to load module Ged
Failed to load module Recorder
Failed to load module FFTW
Failed to load module GuiBld
Failed to load module Vc
Failed to load module ROOTWebDisplay
Failed to load module RooFitCore
Failed to load module Gui
Failed to load module SQLIO
Failed to load module XMLIO
Failed to load module ROOT_Rtypes
Failed to load module std
Failed to load module ROOTHistDraw
Failed to load module RIO
Failed to load module ProofPlayer
Failed to load module ROOTTMVASofie
Failed to load module ASImage
Failed to load module ROOT_Foundation_C
Failed to load module MathMore
Failed to load module RooFitHS3
Failed to load module Foam
Failed to load module RSQLite
Failed to load module SpectrumPainter
Failed to load module Minuit2
Failed to load module Core
Failed to load module MLP
Failed to load module ROOTDataFrame
Failed to load module GenVector
Failed to load module NetxNG
Failed to load module ROOTBrowserv7
Failed to load module Minuit
Failed to load module RootAuth
Failed to load module Graf3d
Failed to load module TMVA
Failed to load module ASImageGui
Failed to load module Graf
Failed to load module Gdml
Failed to load module ProofBench
Failed to load module Cling_Runtime_Extra
Failed to load module MathCore
Failed to load module Gviz3d
Failed to load module WebGui6
Failed to load module ROOTTPython
Failed to load module ROOTHist
Failed to load module TreePlayer
Failed to load module ROOTGraphicsPrimitives
Failed to load module Gviz
Failed to load module ROOTFitPanelv7
Failed to load module Smatrix
Failed to load module SessionViewer
Failed to load module Thread
Assertion failed: (clingInterp.getMacro("gROOT") && "Couldn't load gROOT macro?"), function RegisterCxxModules, file /Users/runner/miniforge3/conda-bld/root_base_1646481338866/work/root-source/core/metacling/src/TCling.cxx, line 1320.

Solution: 
I could handle the problem by downloading Xcode13 and the Command Line Tools for Xcode 13. 

### Installed packages

```shell
# packages in environment at /opt/anaconda3/envs/med:
#
# Name                    Version                   Build  Channel
afterimage                1.21              h4dd67e6_1003    conda-forge
appnope                   0.1.2            py37hf985489_3    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py37h271585c_1    conda-forge
atk-1.0                   2.36.0               he69c4ee_4    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
boost                     1.74.0           py37h326c9ff_5    conda-forge
boost-cpp                 1.74.0               hdbf7018_7    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
c-compiler                1.4.1                h774085c_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cairo                     1.16.0            he01c77b_1009    conda-forge
cctools                   973.0.1             ha54d4a6_10    conda-forge
cctools_osx-64            973.0.1             h609b070_10    conda-forge
certifi                   2021.10.8        py37hf985489_2    conda-forge
cffi                      1.15.0           py37h446072c_0    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
clang                     12.0.1               h694c41f_4    conda-forge
clang-12                  12.0.1          default_he082bbe_4    conda-forge
clang_osx-64              12.0.1               h633439f_8    conda-forge
clangxx                   12.0.1          default_he082bbe_4    conda-forge
clangxx_osx-64            12.0.1               hdb584c0_8    conda-forge
clhep                     2.4.5.1              he49afe7_0    conda-forge
cmake                     3.23.0               h35a7dd9_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
compiler-rt               12.0.1               he01351e_0    conda-forge
compiler-rt_osx-64        12.0.1               hd3f61c9_0    conda-forge
compilers                 1.4.1                h694c41f_0    conda-forge
cxx-compiler              1.4.1                hbb4e6a2_0    conda-forge
davix                     0.8.1                h4c8667f_0    conda-forge
debugpy                   1.5.1            py37hd8d24ac_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h96cf925_0    conda-forge
fftw                      3.3.10          nompi_hf082fe4_102    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.94              h10f422b_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fortran-compiler          1.4.1                h46a1860_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
ftgl                      2.4.0                h508da5b_0    conda-forge
gdk-pixbuf                2.42.8               hb161b9c_0    conda-forge
geant4                    11.0.1           py37he775213_0    conda-forge
geant4-data-abla          3.1                           0    conda-forge
geant4-data-emlow         8.0                  hd8ed1ab_0    conda-forge
geant4-data-ensdfstate    2.3                  hd8ed1ab_0    conda-forge
geant4-data-incl          1.0                           0    conda-forge
geant4-data-ndl           4.6                           0    conda-forge
geant4-data-particlexs    4.0                  hd8ed1ab_0    conda-forge
geant4-data-photonevaporation 5.7                  hd8ed1ab_0    conda-forge
geant4-data-pii           1.3                           1    conda-forge
geant4-data-radioactivedecay 5.6                  hd8ed1ab_0    conda-forge
geant4-data-realsurface   2.2                  hd8ed1ab_0    conda-forge
geant4-data-saiddata      2.0                           0    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
gfortran                  9.3.0               h768ea0c_15    conda-forge
gfortran_impl_osx-64      9.3.0               h9cc0e5e_23    conda-forge
gfortran_osx-64           9.3.0               h18f7dce_15    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
gl2ps                     1.4.2                h4cff582_0    conda-forge
glew                      2.1.0                h046ec9c_2    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
graphviz                  2.50.0               h2b5222e_2    conda-forge
gsl                       2.7                  h93259b0_0    conda-forge
gsoap                     2.8.119              he518799_0    conda-forge
gtk2                      2.24.33              h7c1209e_2    conda-forge
gts                       0.7.6                hccb3bdf_2    conda-forge
harfbuzz                  3.4.0                h447b35c_0    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
importlib-metadata        4.11.3           py37hf985489_1    conda-forge
importlib_resources       5.6.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.11.0           py37h0a7177a_2    conda-forge
ipyparallel               8.2.1              pyhd8ed1ab_0    conda-forge
ipython                   7.32.0           py37hf985489_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isl                       0.22.1               hb1e8313_2    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1           py37hf985489_0    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0d85af4_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.2.1              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py37hf985489_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
ld64                      609                 h4dfd969_10    conda-forge
ld64_osx-64               609                 hc6b1d1e_10    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libclang                  13.0.1          default_he082bbe_0    conda-forge
libclang-cpp12            12.0.1          default_he082bbe_4    conda-forge
libcurl                   7.82.0               h9f20792_0    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgd                     2.3.3                hb8742e1_1    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran-devel_osx-64  9.3.0               h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_4    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_3    conda-forge
libllvm12                 12.0.1               hd011deb_2    conda-forge
libllvm13                 13.0.1               h64f94b2_2    conda-forge
libllvm9                  9.0.1           default_h2671707_7    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     14.2                 hea3049e_0    conda-forge
librsvg                   2.52.5               h5e5d7d9_2    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libtool                   2.4.6             he49afe7_1008    conda-forge
libuv                     1.43.0               h0d85af4_0    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
llvm-tools                12.0.1               hd011deb_2    conda-forge
llvmlite                  0.38.0           py37h464c7a5_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
markupsafe                2.1.1            py37h69ee0a8_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
metakernel                0.29.0             pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py37h271585c_1005    conda-forge
mpc                       1.2.1                hbb51d92_0    conda-forge
mpfr                      4.1.0                h0f52abe_1    conda-forge
mysql-common              8.0.28               hab7e275_2    conda-forge
mysql-libs                8.0.28               h2a44bf5_2    conda-forge
nbclient                  0.5.13             pyhd8ed1ab_0    conda-forge
nbconvert                 6.4.5              pyhd8ed1ab_2    conda-forge
nbconvert-core            6.4.5              pyhd8ed1ab_2    conda-forge
nbconvert-pandoc          6.4.5              pyhd8ed1ab_2    conda-forge
nbformat                  5.2.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
nlohmann_json             3.10.5               he49afe7_0    conda-forge
notebook                  6.4.10             pyha770c72_0    conda-forge
nspr                      4.32                 hcd9eead_1    conda-forge
nss                       3.77                 hfce436b_0    conda-forge
numba                     0.55.1           py37h078fc1e_0    conda-forge
numpy                     1.21.5           py37h3c8089f_0    conda-forge
openssl                   1.1.1n               h6c3fc93_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandoc                    2.17.1.1             h694c41f_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.50.3               h7f27720_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
portalocker               2.4.0            py37hf985489_0    conda-forge
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
psutil                    5.9.0            py37h69ee0a8_1    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py37h69ee0a8_1    conda-forge
pythia8                   8.305            py37hd8d24ac_0    conda-forge
python                    3.7.12          haf480d7_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pyzmq                     22.3.0           py37h8f778e5_1    conda-forge
qt                        5.12.9               h2a607e2_5    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
rhash                     1.4.1                h0d85af4_0    conda-forge
root                      6.26.0           py37h635a340_0    conda-forge
root_base                 6.26.0           py37h7165b58_0    conda-forge
scitokens-cpp             0.6.3                h27338ba_2    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                61.3.1           py37hf985489_0    conda-forge
sigtool                   0.1.3                h57ddcff_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.1               hb516253_0    conda-forge
tapi                      1100.0.11            h9ce4665_0    conda-forge
tbb                       2021.5.0             h940c156_0    conda-forge
terminado                 0.13.3           py37hf985489_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.1              py37h69ee0a8_3    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
vdt                       0.4.3                h046ec9c_0    conda-forge
vector-classes            1.4.2                h940c156_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h6564042_4    conda-forge
xorg-kbproto              1.0.7             h35c211d_1002    conda-forge
xorg-libice               1.0.10               h0d85af4_0    conda-forge
xorg-libsm                1.2.3             h0d85af4_1000    conda-forge
xorg-libx11               1.7.2                h0d85af4_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xorg-libxext              1.3.4                h0d85af4_1    conda-forge
xorg-libxmu               1.1.3                h0d85af4_0    conda-forge
xorg-libxt                1.2.1                h0d85af4_2    conda-forge
xorg-xextproto            7.3.0             h35c211d_1002    conda-forge
xorg-xproto               7.0.31            h35c211d_1007    conda-forge
xrootd                    5.4.1            py37he6b4dc7_0    conda-forge
xxhash                    0.8.0                h35c211d_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```

### Environment info

```shell
active environment : med
    active env location : /opt/anaconda3/envs/med
            shell level : 2
       user config file : /Users/admin/.condarc
 populated config files : /Users/admin/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/admin/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/admin/.conda/envs
               platform : osx-64
             user-agent : conda/4.12.0 requests/2.26.0 CPython/3.9.7 Darwin/21.4.0 OSX/10.16
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```

**Comment by chrisburr** [comment] 2022-04-05 11:42
I think this is a duplicate of #149 which is caused by a bug in ROOT. I've just pinged the experts about it again about getting it fixed.

In the meantime there is a workaround mentioned in https://github.com/conda-forge/root-feedstock/issues/149#issuecomment-1066560467.

**Closed by chrisburr** 2022-04-05 11:42 UTC
Labels: bug
